const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{Sprite: 0},
	{terra: 0},
	{Sprite2: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{pixinho: 0},
	{esquerda: 0},
	{direita: 0},
	{pulo: 0},
	{Toque: 0},
	{patafoma: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{entrada: 0},
	{particulaCaixa: 0},
	{xavi: 0},
	{paxicula: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Senóide: 0},
	{meninoEnimigo: 0},
	{Áudio: 0},
	{Sprite8: 0},
	{inha: 0},
	{Sprite9: 0},
	{botao: 0},
	{Puticula: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{saida: 0},
	{txtchave: 0},
	{txtVidas: 0},
	{Sprite5: 0},
	{Sprite10: 0},
	{estado: 0},
	{xave: 0},
	{vida: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	terra: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	pixinho: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	pulo: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	patafoma: class extends self.ITiledBackgroundInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	entrada: class extends self.ISpriteInstance {},
	particulaCaixa: class extends self.IParticlesInstance {},
	xavi: class extends self.ISpriteInstance {},
	paxicula: class extends self.IParticlesInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	meninoEnimigo: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	inha: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	botao: class extends self.ISpriteInstance {},
	Puticula: class extends self.IParticlesInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	saida: class extends self.ISpriteInstance {},
	txtchave: class extends self.ITextInstance {},
	txtVidas: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}